### ISSUE TITLE
data for classification example?

### ISSUE THREAD

**Issue by jgh-** [aria42/tensors#2]
Hi,

Your classification example references datasets that aren't available in your repo, nor are they easily googleable.  It would be great if you could include them in the repo so that the example project could work out of the box.

**Comment by NonaryR** [comment]
I think [that's it](http://ai.stanford.edu/~amaas/data/sentiment/)
Glove vectors you can find [here](https://nlp.stanford.edu/projects/glove/ )
But I agree, which folders and data in `Movie review dataset` - not so clean
Because in code I see `sentiment-train10k` and in dataset above we have 25k pos and 25k neg examples, without tags

**Comment by aria42** [comment]
This is because you don't have Intel MKL installed. The readme mentions needing to have those native libs installed (and you also need to disable System Integrity Protection) to load libraries from non-standard locations since Intel installs these under `/opt/` typically.

**Comment by aria42** [comment]
Hey there, sorry for the confusion @jgh- . This class is meant to train any kind of sentence classification model and the comment @NonaryR mentioned is just to give an example of calling things programmatically. 

I added a comment to the documentation of the class to give the format for embeddings and train/test with a link to data formatted in this way. The data I used in the blog post is the Sentiment data, and I interleaved the positive and negative data and randomly sampled 10k for the train/test files. I don't know if I can re-distribute them, but can share a dropbox link

**Comment by aria42** [comment]
Oh here's the link to the doc: http://aria42.com/flare/flare.examples.sentence-classification.html

**Comment by NonaryR** [comment]
@aria42 can you post dropbox link here? it will be helpful

**Comment by aria42** [comment]
Hey @NonaryR , I've uploaded the [train data](https://www.dropbox.com/s/a9hgh3pvp1zzlnc/sentiment-train10k.txt?dl=0) and [test data](https://www.dropbox.com/s/eup8rnprv76ytoi/sentiment-test10k.txt?dl=0) used for the blog post and here's [the CLI output](https://gist.github.com/aria42/c8a6a95718d581cf3446eac0002d13b3) for train/test on a jar built from master head (3e5baa17153b), I can recreate the numbers same as the blog post (note the reported numbers are averages) after a few iterations. Numbers are a little faster due to some more usage of vector arithmetic operations. 

If you look at #5 there's a PR to run everything as a script but seems to have some issues, but might give you what you want

**Comment by aria42** [comment]
Good to close @NonaryR ?

**Comment by NonaryR** [comment]
@aria42  yes, thank you! I can't wait to new features!
